40 write route for viewing a single neighborhood
neighborhood-app/app pull request #67
Opened 2023-05-03 18:15 UTC by RobertRodes

I think this one might be ready to close.

2023-05-03 21:40 UTC, MaxHass12 reviewed
It looks perfect. (apart from very minor things discovered by `nom run lint`). Approving.

2023-05-04 03:48 UTC, radu-constantin commented
> It looks perfect. (apart from very minor things discovered by `nom run lint`). Approving.

Great job Bob! Works fine!
I also confirm what Shwetank said above and I want to add that it would be helpful to install the eslint VSCode extension so you can better see linting errors.
Also, I noticed that the 'GET /neighborhoods/id invalid id returns expected error' test is outside the `describe` block.
These are not critical issues so I will approve the pull request and we can fix them later.

2023-05-04 03:50 UTC, radu-constantin approved these changes

2023-05-04 03:50 UTC, radu-constantin commented on src/tests/neighborhood_api.test.ts
>  });
This should be inside a describe block

2023-05-04 11:07 UTC, nina-dk reviewed
I'm also getting some minor ESLint complaints. Other than that, and what I've mentioned about the tests, looking good 👌🏻

2023-05-04 11:07 UTC, nina-dk commented on src/tests/neighborhood_api.test.ts
Shouldn't these tests be in their own `describe` block?

2023-05-04 16:19 UTC, RobertRodes commented on src/tests/neighborhood_api.test.ts
I've moved my test into the `describe` block, and resolved conflict.

2023-05-07 10:48 UTC, nina-dk requested changes

2023-05-07 10:48 UTC, nina-dk commented on src/controllers/neighborhoods.ts
Is the route duplicated or am I missing something?

2023-05-07 11:27 UTC, radu-constantin commented on src/controllers/neighborhoods.ts
Just checked it out, you're right, it is duplicated.

2023-05-07 12:59 UTC, RobertRodes commented on src/controllers/neighborhoods.ts
Ok, now I see it. So, we should create an issue to remove the duplicate route?

2023-05-07 13:14 UTC, radu-constantin commented on src/controllers/neighborhoods.ts
Exactly!

2023-05-07 13:20 UTC, RobertRodes commented on src/controllers/neighborhoods.ts
> Exactly!

All right. I will make the modification and push it.

2023-05-08 23:21 UTC, merged

2023-05-08 23:22 UTC, RobertRodes commented
Ok, I think this one's done.